sahakirala/Controllers/AramaController.cs
using Database;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.UI.WebControls;
using PagedList;

namespace sahakirala.Controllers
{
    public class AramaController : Controller
    {
        SportsSideWebApi.Controllers.SportsSideApiController webApi = new SportsSideWebApi.Controllers.SportsSideApiController();
        // GET: Arama
        public ActionResult Index(int? page, string SearchString, string FacilityType, string ddlAreas, string ddlCities, string ddlDistricts, string Price1, string Price2, string enlem, string boylam)
        {
            string role = new Business.AccountBusiness().currentMember();
            if (role != "U" && role != "A" && role != "O")
            {
                return RedirectToAction("Login", "Account");
            }
            DatabaseEntities db = new DatabaseEntities();
            string cookieName = FormsAuthentication.FormsCookieName; //Find cookie name
            HttpCookie authCookie = HttpContext.Request.Cookies[cookieName]; //Get the cookie by it's name
            FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(authCookie.Value); //Decrypt it
            string UserName = ticket.Name; //You have the UserName!
            var rowFind = db.USERS.FirstOrDefault(x => x.USER_NAME == UserName);
            var district = rowFind.USER_DISTRICT;
            List<FACILITY> facilityList = db.FACILITies.Where(a => a.DISTRICT_ID == district).ToList();
            IEnumerable<FACILITY> facilityIE = facilityList;
            var facilities = facilityIE;
            ViewBag.Areas = new SelectList(webApi.GetAreas(), "AREA_ID", "AREA_NAME");

            if (enlem != null && boylam != null)
            {
                string url = "http://maps.googleapis.com/maps/api/geocode/json?latlng=" + enlem + "," + boylam + "&sensor=true";
                HttpWebRequest request = WebRequest.Create(url) as HttpWebRequest;
                string jsonVerisi = "";
                using (HttpWebResponse response = request.GetResponse() as HttpWebResponse)
                {
                    StreamReader reader = new StreamReader(response.GetResponseStream());
                    jsonVerisi = reader.ReadToEnd();
                }
                var obj = JObject.Parse(jsonVerisi);

                var user = JsonConvert.DeserializeObject<GoogleGeoCodeResponse>(jsonVerisi);
                var yer = user.results[0].address_components[0].long_name;
                var mevki = user.results[0].address_components[1].long_name;
                var mahalle = user.results[0].address_components[2].long_name;
                var ilce = user.results[0].address_components[3].long_name;
                var il = user.results[0].address_components[4].long_name;

                var distList = db.DISTRICTs.FirstOrDefault(a => a.DISTRICT_NAME == ilce);

                var facility = db.FACILITies.Where(a => a.DISTRICT_ID == distList.DISTRICT_ID).ToList();
                //IEnumerable<FACILITY> facilityIE = facility;


                //rowFind.USER_DISTRICT = distList.DISTRICT_ID;

                //db.Entry(rowFind).State = EntityState.Modified;
                //db.SaveChanges();
                return View(facility);
            }



            if (!String.IsNullOrEmpty(ddlAreas))
            {
                facilities = db.FACILITies.Where(a => a.DISTRICT.CITY.AREA_ID.ToString() == ddlAreas).ToList();
            }
            if (!String.IsNullOrEmpty(ddlCities))
            {
                facilities = db.FACILITies.Where(x => x.DISTRICT.CITY_ID.ToString() == ddlCities).ToList();
            }
            if (!String.IsNullOrEmpty(ddlDistricts))
            {
                facilities = db.FACILITies.Where(x => x.DISTRICT_ID.ToString() == ddlDistricts).ToList();
            }
            if (String.IsNullOrEmpty(ddlAreas) && String.IsNullOrEmpty(ddlCities) && String.IsNullOrEmpty(ddlDistricts) && !String.IsNullOrEmpty(SearchString))
            {
                facilities = db.FACILITies.Where(x => x.FACILITY_NAME.StartsWith(SearchString)).ToList();
            }
            if (Price1 != null && Price1 != "")
            {
                int PriceMin = Int32.Parse(Price1);
                facilities = facilities.Where(a => a.FACILITY_PRICE >= PriceMin);
            }
            if (Price2 != null && Price2 != "")
            {
                int PriceMax = Int32.Parse(Price2);
                facilities = facilities.Where(a => a.FACILITY_PRICE <= PriceMax).ToList();
            }
            if (!String.IsNullOrEmpty(FacilityType) && FacilityType != "Tesis Türü Seç")
            {
                facilities = facilities.Where(x => x.FACILITY_TYPE1.FT_NAME == FacilityType).ToList();
            }
            if ((!String.IsNullOrEmpty(ddlAreas) || !String.IsNullOrEmpty(ddlCities) || !String.IsNullOrEmpty(ddlDistricts)) && !String.IsNullOrEmpty(SearchString))
            {
                var newFacilities = db.FACILITies.Where(x => x.FACILITY_NAME.StartsWith(SearchString));
                facilities = newFacilities.Where(x => x.DISTRICT_ID.ToString() == ddlDistricts).ToList();
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(facilities.ToPagedList(pageNumber, pageSize));
        }

        public string DistrictByCityId(int cityId)
        {
            string sonuc = "";
            DatabaseEntities db = new DatabaseEntities();
            var ilceler = db.DISTRICTs.Where(a => a.CITY_ID == cityId).ToList();
            return sonuc;
        }
    }
}

sahakirala/Views/Arama/Index.cshtml
@model PagedList.IPagedList<Database.FACILITY>
@using PagedList.Mvc;
@{
    ViewBag.Title = "SportSide - Arama";
    Layout = "~/Views/Shared/_RezervasyonLayout.cshtml";
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/js/jsArama.js"></script>
<script src="~/js/jquery.inputmask.bundle.js"></script>


<h2>Arama Formu</h2>
@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-md-6">
            @Html.TextBox("SearchString", null, new { @class = "form-control", placeholder = "Tesis İsmini Giriniz", @id = "SearchString" })
        </div>

        <div class="form-group col-md-6">
                @Html.DropDownList("ddlAreas", ViewBag.Areas as SelectList, "Seçiniz", new { @class = "form-control input-sm select2search", id = "ddlAreas"})
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <select class="form-control" id="FacilityType" name="FacilityType">
                <option>Tesis Türü Seç</option>
            </select>
        </div>

        <div class="form-group col-md-6">
            @Html.DropDownList("ddlCities", Enumerable.Empty<SelectListItem>(), "Bölge Seçiniz", new { @class = "form-control input-sm select2search", id = "ddlCities" })
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            @Html.TextBox("Price1", null, new { @class = "form-control", placeholder = "Düşük Fiyatı Giriniz", @id = "Price1" })
        </div>

        <div class="col-md-3">
            @Html.TextBox("Price2", null, new { @class = "form-control", placeholder = "Yüksek Fiyatı Giriniz", @id = "Price2" })
        </div>
        <div class="col-md-6">
            @Html.DropDownList("ddlDistricts", Enumerable.Empty<SelectListItem>(), "Şehir Seçiniz", new { @class = "form-control input-sm select2search", id = "ddlDistricts" })
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <button class="form-control araBtn" id="@Url.Action("Index", "Arama")"><i class="fa fa-search" aria-hidden="true"></i> Ara</button>
        </div>
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-hover table-bordered" style="margin-top:50px;">
                <tr>
                    <th>Tesis Adı</th>
                    <th>İl</th>
                    <th>İlçe</th>
                    <th>Fiyat</th>
                    <th>Kapasite</th>
                    <th>Tesis Türü</th>
                    <th></th>
                </tr>
                @foreach (var item in @Model)
                {

                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.FACILITY_NAME)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DISTRICT.CITY.CITY_NAME)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DISTRICT.DISTRICT_NAME)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FACILITY_PRICE)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FACILITY_CAPACITY)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FACILITY_TYPE1.FT_NAME)
                        </td>
                        @*<td><a href="@Url.Action("Index", "Reservation", new { id = item.FACILITY_ID})">Seç</a></td>*@
                        <td style="text-align:center;">
                            <input type="button" onclick="location.href='@Url.Action("Index", "Reservation", new { id = item.FACILITY_ID})'" class="btn btn-primary" value="Seç"/>
                        </td>
                    </tr>
                }
            </table>
            <ul class="pager">
                <li class="next">

                    @*Sayfalandırma kodu*@
                    <br /> Sayfa @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))

                </li>
            </ul>
        </div>
    </div>
        @*
            <tr>
                <td>Serdivan Halı Saha</td>
                <td>Sakarya</td>
                <td>Serdivan</td>
                <td>Kemalpaşa</td>
                <td>100 TL</td>
                <td>14</td>
                <td>Futbol</td>
                <td><a href="#">Seç</a></td>
            </tr>
            <tr>
                <td>Söğütlü Halı Saha</td>
                <td>Sakarya</td>
                <td>Söğütlü</td>
                <td>Mahalle</td>
                <td>120 TL</td>
                <td>14</td>
                <td>Futbol</td>
                <td><a href="#">Seç</a></td>
            </tr>
            <tr>
                <td>Sakarya Üniversitesi Salonu</td>
                <td>Sakarya</td>
                <td>Serdivan</td>
                <td>Kampüs</td>
                <td>50 TL</td>
                <td>10</td>
                <td>Basketbol</td>
                <td><a href="#">Seç</a></td>
            </tr>*@

        @*}*@
}

@*<script>
    function cityChanged() {
        debugger;
        var e = document.getElementById("_CityId");
        var Id = e.options[e.selectedIndex].value;
        var url = '@Url.Action("DistrictByCityId", "Arama")';
        $.post(url, Id, function (result) {
            //ada.calljx('/Home/DistrictByCityId', { cityId: Id }, 'body', function (d) {
                debugger;
            //ada.ajaxReturn(d, function (data) {
            //    $('#_DistrictId').empty();
            //    $('#_DistrictId').select2('data', null);
            //    $('#_DistrictId').select2('data', { text: 'Seçiniz', id: '' });
            //    $.each(data.liste, function (i, e) {
            //        var x = document.getElementById("_DistrictId");
            //        var option = document.createElement("option");
            //        option.text = e.IlceAdi;
            //        option.value = e.IlceAdi;
            //        x.add(option);
            //    });
            //});
        });
    }
</script>*@

@*<script>
        function cityChanged() {
            var e = document.getElementById("_AreaId");
            var Id = e.options[e.selectedIndex].value;
            $("#_CityId").empty();
            $.ajax({
                type: "GET",
                dataType: "json",
                url: "http://localhost:4285/SSApi/GetCitiesByAreas",
                data: { areaId: Id },
                success: function (data) {
                    $(data).each(function (key, item) {
                        $("#_CityId").append(
                            $("<option></option>").val(item.CITY_ID).html(item.CITY_NAME)
                        );
                    });
                },
                error: function (req, status, err) {
                    console.log("HATA : ", req, status, err);
                }
            });
        };
</script>*@

<script>
            $(document).ready(function () {
                //var x = document.getElementById("demo");
                debugger;
                if (navigator.geolocation) {
                    navigator.geolocation.watchPosition(showPosition);
                }
                else {
                    x.innerHTML = "Geolocation is not supported by this browser.";
                }
            });

            function showPosition(position) {
                debugger;
                var enlem = position.coords.latitude;
                var boylam = position.coords.longitude;
                var url = "/Arama/Index";
                var data = { enlem: enlem, boylam: boylam };


                $.post(url, data, function (result) {
                    // TODO: do something with the response from the controller action
                });

                //x.innerHTML = "Latitude: " + position.coords.latitude +
                //"<br>Longitude: " + position.coords.longitude;
            }
</script>