sahakirala/Controllers/MemberController.cs
using Database;
using sahakirala.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using PagedList;

namespace sahakirala.Controllers
{
    public class MemberController : Controller
    {
        SportsSideWebApi.Controllers.SportsSideApiController webApi = new SportsSideWebApi.Controllers.SportsSideApiController();

        // GET: Member
        public ActionResult Index(int? pageActive, int? pageHistory, int? pageSub, int? selectedTab)
        {
            string role = new Business.AccountBusiness().currentMember();
            if (role != "U" && role != "A" && role != "O")
            {
                return RedirectToAction("Login", "Account");
            }
            if (selectedTab != null)
            {
                TempData["selectedTab"] = selectedTab;
            }
            int pageSize = 10;
            int pageNumberActive = (pageActive ?? 1);
            int pageNumberHistory = (pageHistory ?? 1);
            int pageNumberSub = (pageSub ?? 1);
            TempData["selectedTab"] = TempData["selectedTab"] == null ? 0 : TempData["selectedTab"];

            DatabaseEntities db = new DatabaseEntities();

            string cookieName = FormsAuthentication.FormsCookieName;
            HttpCookie authCookie = HttpContext.Request.Cookies[cookieName];
            FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(authCookie.Value);
            string userName = ticket.Name;
            var user = webApi.GetUser(userName);
            var liveReservations = webApi.liveReservations(user.USER_ID);
            var subscribers = webApi.GetSubscribersByUserId(user.USER_ID);
            var oldReservations = webApi.oldReservations(user.USER_ID);
            List<SportsSide.DAL.RESERVATION> newLiveReservations = new List<SportsSide.DAL.RESERVATION>();
            List<SportsSide.DAL.RESERVATION> newOldReservations = new List<SportsSide.DAL.RESERVATION>();
            foreach (var item in liveReservations)
            {
                if (item.DT_BEGIN.Date > DateTime.Now.Date || (item.DT_BEGIN.Date == DateTime.Now.Date && item.DT_BEGIN.Hour > DateTime.Now.Hour))
                {
                    newLiveReservations.Add(item);
                }
            }
            foreach (var item in oldReservations)
            {
                if (item.DT_BEGIN.Date < DateTime.Now.Date || (item.DT_BEGIN.Date == DateTime.Now.Date && item.DT_BEGIN.Hour < DateTime.Now.Hour))
                {
                    newOldReservations.Add(item);
                }
            }
            MemberBigModel model = new MemberBigModel();
            model.User = user;
            model.LiveReservations = newLiveReservations.OrderByDescending(x => x.CREATED_DATE).ToPagedList(pageNumberActive, pageSize);
            model.oldReservations = newOldReservations.OrderByDescending(x => x.CREATED_DATE).ToPagedList(pageNumberHistory, pageSize);
            model.Subscribers = subscribers.OrderByDescending(x => x.CREATED_DATE).ToPagedList(pageNumberSub, pageSize);
            model.selectedTab = TempData["selectedTab"].ToString();

            model.Date = System.DateTime.Now.Date;


            ViewBag.Areas = new SelectList(webApi.GetAreas(), "AREA_ID", "AREA_NAME", user.DISTRICT.CITY.AREA.AREA_ID);
            ViewBag.Cities = new SelectList(webApi.GetCitiesByAreas(user.DISTRICT.CITY.AREA.AREA_ID), "CITY_ID", "CITY_NAME");
            ViewBag.Districts = new SelectList(webApi.GetDistrictsByCities(user.DISTRICT.CITY.CITY_ID), "DISTRICT_ID", "DISTRICT_NAME");

            return View(model);
        }

        [HttpPost]
        public ActionResult Index(MemberBigModel model)
        {
            var result = false;
            int pageSize = 10;
            int pageNumberActive = 1;
            int pageNumberHistory = 1;
            int pageNumberSub = 1;
            if (!ModelState.IsValid)
            {
                result = webApi.PutUser(model.User);
                if (result == false)
                {
                    TempData["Hata"] = "Bir hata oluştu.";
                    var user1 = webApi.GetUser(model.User.USER_ID);
                    ViewBag.Areas = new SelectList(webApi.GetAreas(), "AREA_ID", "AREA_NAME", user1.DISTRICT.CITY.AREA.AREA_ID);
                    ViewBag.Cities = new SelectList(webApi.GetCitiesByAreas(user1.DISTRICT.CITY.AREA.AREA_ID), "CITY_ID", "CITY_NAME");
                    ViewBag.Districts = new SelectList(webApi.GetDistrictsByCities(user1.DISTRICT.CITY.CITY_ID), "DISTRICT_ID", "DISTRICT_NAME");

                    var liveReservations = webApi.liveReservations(user1.USER_ID);
                    var subscribers = webApi.GetSubscribersByUserId(user1.USER_ID);
                    var oldReservations = webApi.oldReservations(user1.USER_ID);
                    List<SportsSide.DAL.RESERVATION> newLiveReservations = new List<SportsSide.DAL.RESERVATION>();
                    List<SportsSide.DAL.RESERVATION> newOldReservations = new List<SportsSide.DAL.RESERVATION>();
                    foreach (var item in liveReservations)
                    {
                        if (item.DT_BEGIN.Date > DateTime.Now.Date || (item.DT_BEGIN.Date == DateTime.Now.Date && item.DT_BEGIN.Hour > DateTime.Now.Hour))
                        {
                            newLiveReservations.Add(item);
                        }
                    }
                    foreach (var item in oldReservations)
                    {
                        if (item.DT_BEGIN.Date < DateTime.Now.Date || (item.DT_BEGIN.Date == DateTime.Now.Date && item.DT_BEGIN.Hour < DateTime.Now.Hour))
                        {
                            newOldReservations.Add(item);
                        }
                    }
                    MemberBigModel bigModel = new MemberBigModel();
                    model.User = user1;
                    model.LiveReservations = newLiveReservations.OrderByDescending(x => x.CREATED_DATE).ToPagedList(pageNumberActive, pageSize);
                    model.oldReservations = newOldReservations.OrderByDescending(x => x.CREATED_DATE).ToPagedList(pageNumberHistory, pageSize);
                    model.Subscribers = subscribers.OrderByDescending(x => x.CREATED_DATE).ToPagedList(pageNumberSub, pageSize);
                    model.selectedTab = "1";

                    model.Date = System.DateTime.Now.Date;

                    ViewBag.Areas = new SelectList(webApi.GetAreas(), "AREA_ID", "AREA_NAME", user1.DISTRICT.CITY.AREA.AREA_ID);
                    ViewBag.Cities = new SelectList(webApi.GetCitiesByAreas(user1.DISTRICT.CITY.AREA.AREA_ID), "CITY_ID", "CITY_NAME");
                    ViewBag.Districts = new SelectList(webApi.GetDistrictsByCities(user1.DISTRICT.CITY.CITY_ID), "DISTRICT_ID", "DISTRICT_NAME");

                    return View(model);
                }
                return RedirectToAction("Index", "Arama");
            }
            else
            {
                TempData["Hata"] = "Bir hata oluştu.";
                var user1 = webApi.GetUser(model.User.USER_ID);
                ViewBag.Areas = new SelectList(webApi.GetAreas(), "AREA_ID", "AREA_NAME", user1.DISTRICT.CITY.AREA.AREA_ID);
                ViewBag.Cities = new SelectList(webApi.GetCitiesByAreas(user1.DISTRICT.CITY.AREA.AREA_ID), "CITY_ID", "CITY_NAME");
                ViewBag.Districts = new SelectList(webApi.GetDistrictsByCities(user1.DISTRICT.CITY.CITY_ID), "DISTRICT_ID", "DISTRICT_NAME");

                var liveReservations = webApi.liveReservations(user1.USER_ID);
                var subscribers = webApi.GetSubscribersByUserId(user1.USER_ID);
                var oldReservations = webApi.oldReservations(user1.USER_ID);
                List<SportsSide.DAL.RESERVATION> newLiveReservations = new List<SportsSide.DAL.RESERVATION>();
                List<SportsSide.DAL.RESERVATION> newOldReservations = new List<SportsSide.DAL.RESERVATION>();
                foreach (var item in liveReservations)
                {
                    if (item.DT_BEGIN.Date > DateTime.Now.Date || (item.DT_BEGIN.Date == DateTime.Now.Date && item.DT_BEGIN.Hour > DateTime.Now.Hour))
                    {
                        newLiveReservations.Add(item);
                    }
                }
                foreach (var item in oldReservations)
                {
                    if (item.DT_BEGIN.Date < DateTime.Now.Date || (item.DT_BEGIN.Date == DateTime.Now.Date && item.DT_BEGIN.Hour < DateTime.Now.Hour))
                    {
                        newOldReservations.Add(item);
                    }
                }
                MemberBigModel bigModel = new MemberBigModel();
                model.User = user1;
                model.LiveReservations = newLiveReservations.OrderByDescending(x => x.CREATED_DATE).ToPagedList(pageNumberActive, pageSize);
                model.oldReservations = newOldReservations.OrderByDescending(x => x.CREATED_DATE).ToPagedList(pageNumberHistory, pageSize);
                model.Subscribers = subscribers.OrderByDescending(x => x.CREATED_DATE).ToPagedList(pageNumberSub, pageSize);
                model.selectedTab = "1";

                model.Date = System.DateTime.Now.Date;

                ViewBag.Areas = new SelectList(webApi.GetAreas(), "AREA_ID", "AREA_NAME", user1.DISTRICT.CITY.AREA.AREA_ID);
                ViewBag.Cities = new SelectList(webApi.GetCitiesByAreas(user1.DISTRICT.CITY.AREA.AREA_ID), "CITY_ID", "CITY_NAME");
                ViewBag.Districts = new SelectList(webApi.GetDistrictsByCities(user1.DISTRICT.CITY.CITY_ID), "DISTRICT_ID", "DISTRICT_NAME");

                return View(model);
            }
        }
        [HttpGet]
        public bool RejectSubscriber(int id)
        {
            SportsSide.DAL.SUBSCRIBER model = new SportsSide.DAL.SUBSCRIBER();
            model = webApi.GetSubscriberFromSubscriberId(id);

sahakirala/Views/Shared/_Layout.cshtml
@model Database.USER
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="~/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="~/css/idangerous.swiper.css" rel="stylesheet" type="text/css">
    <link href="~/css/devices.min.css" rel="stylesheet" type="text/css">
    <link href="~/css/style.css" rel="stylesheet" type="text/css">
    <link href="~/css/animate.css" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" href="~/img/favicon.ico">
    <title>SportsSide - 30 Saniyede Saha Kirala!</title>
    <style type="text/css">
        .gm-style .gm-style-mtc label, .gm-style .gm-style-mtc div {
            font-weight: 400;
        }
    </style>
    <link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <style type="text/css">
        .gm-style .gm-style-cc span, .gm-style .gm-style-cc a, .gm-style .gm-style-mtc div {
            font-size: 10px;
        }
    </style>

    <style type="text/css">
        .gm-style {
            font: 400 11px Roboto, Arial, sans-serif;
            text-decoration: none;
        }

            .gm-style img {
                max-width: none;
            }
    </style>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    @*<script type="text/javascript" charset="UTF-8" src="http://maps.googleapis.com/maps-api-v3/api/js/28/3/common.js"></script>
        <script type="text/javascript" charset="UTF-8" src="http://maps.googleapis.com/maps-api-v3/api/js/28/3/util.js"></script>
        <script type="text/javascript" charset="UTF-8" src="http://maps.googleapis.com/maps-api-v3/api/js/28/3/stats.js"></script>
        <script type="text/javascript" charset="UTF-8" src="http://maps.googleapis.com/maps-api-v3/api/js/28/3/map.js"></script>
        <script type="text/javascript" charset="UTF-8" src="http://maps.googleapis.com/maps-api-v3/api/js/28/3/marker.js"></script>
        <script type="text/javascript" charset="UTF-8" src="http://maps.googleapis.com/maps-api-v3/api/js/28/3/onion.js"></script>
        <script type="text/javascript" charset="UTF-8" src="http://maps.googleapis.com/maps-api-v3/api/js/28/3/controls.js"></script>
        <script type="text/javascript" charset="UTF-8" src="http://maps.googleapis.com/maps-api-v3/api/js/28/3/infowindow.js"></script>*@
    <script src="~/js/jquery-2.1.3.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/idangerous.swiper.min.js"></script>
    <script src="~/js/global.js"></script>

    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;language=en"></script>
    <script src="~/js/map.js"></script>

    <script src="~/js/wow.min.js"></script>
    <script src="~/js/subscription.js"></script>

    <script src="~/Scripts/mayki.js"></script>
    
    <style>
        .carousel-inner > .item > img,
        .carousel-inner > .item > a > img {
            width: 70%;
            margin: auto;
        }
    </style>
</head>
<body data-theme="theme-3">

    <header class="">
        <a href="#" id="logo"><img src="~/img/theme-3/30.png" alt=""><img class="act" src="~/img/theme-3/32.png" alt=""></a>
        <div class="mob-icon">
            <span></span>
        </div>
        <nav>
            <ul>
                <li><a href="#home" class="scroll-to-link act">GİRİŞ</a></li>
                <li><a href="#about" class="scroll-to-link">NEDEN</a></li>
                <li><a href="#why" class="scroll-to-link">NASIL</a></li>
                <li><a href="#benefits" class="scroll-to-link">ARTILAR</a></li>
                <li><a href="#how-it-work" class="scroll-to-link">SİSTEM</a></li>
                <li><a href="#contact" class="scroll-to-link">İLETİŞİM</a></li>
            </ul>
        </nav>
    </header>

    <div id="loader-wrapper">
        <img src="~/img/theme-3/30.png" alt="">
        <span></span>
    </div>

    <div class="body-content">
        @RenderBody()
    </div>


    <style>
        .site-footer h3{
            font-size:18px;
        }
        .ulSayfa li{
            list-style:none !important;
        }
        .footerChapter{
            margin-top:10px;
            margin-left:0px;
        }
        .footerChapter a{
            color:#ccc;
        }
        .footerChapter a:hover{
            text-decoration:none;
            color:#ccc;
        }
    </style>
    <!-- FOOTER -->
    <footer class="site-footer">
        <div class="bottom-footer" style="padding:50px;">
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <h3>SportsSide Hakkında</h3>
                        <p class="footerChapter">
                            <i class="fa fa-chevron-right" style="margin-right:5px;" aria-hidden="true"></i>SportsSide, online spor tesisi kiralama sistemidir.
                        </p>
                        <p class="footerChapter">
                            <i class="fa fa-chevron-right" style="margin-right:5px;" aria-hidden="true"></i>Rezervasyon yapabilir, yakındaki veya Türkiyenin herhangi bir yerinde sahayı bulabilirsiniz.
                        </p>
                    </div>
                    <div class="col-md-5 col-md-offset-1">
                        <h3>İletişim</h3>
                        <div class="row footerChapter">
                            <a class="contact-link"><i class="fa fa-map-marker" style="margin-right:5px;"></i> Eski Büyükdere Cad. Yamaç Sk. No: 6/4, 4. Serdivan / Sakarya</a>
                        </div>
                        <div class="row footerChapter">
                            <a class="contact-link"><i class="fa fa-phone" style="margin-right:5px;"></i> +90 (212) 269 70 87</a>
                        </div>
                        <div class="row footerChapter">
                            <a class="contact-link"><i class="fa fa-fax" style="margin-right:5px;"></i> +90 (212) 269 16 22</a>
                        </div>        
                        <div class="row footerChapter">
                            <a class="contact-link"><i class="fa fa-envelope" style="margin-right:5px;"></i> info@sportsside.net</a>
                        </div>    
                                               
                    </div>
                    <div class="col-md-2">
                        <h3>Sayfalar</h3>
                        <div class="row footerChapter">
                            <a href="/Home/Index"><i class="fa fa-globe" style="margin-right:7px;" aria-hidden="true"></i>Ana Sayfa</a>
                        </div>
                        <div class="row footerChapter">
                            <a href="/Arama/Index"><i class="fa fa-search" style="margin-right:5px;" aria-hidden="true"></i>Tesis Arama</a>
                        </div>        
                        <div class="row footerChapter">
                            <a href="/Member/Index"><i class="fa fa-user" style="margin-right:8px;" aria-hidden="true"></i>Kullanıcı Bilgi</a>
                        </div>       
                                
                    </div>
                </div>
            </div>
        </div>

    </footer>

</body>
</html>

sahakirala/Views/Shared/_PartialReservationSummary.cshtml
@model sahakirala.Models.ReservationBigModel

<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">Rezervasyon Özeti</h3>
    </div>
    <div class="panel-body">
        <div class="col-md-12">
            <dl class="dl-horizontal">
                <dt><span class="label" id="myLabel">Tesis Adı :</span></dt>
                <dd>@Model.Facility.FACILITY_NAME</dd>
                <dt><span class="label" id="myLabel">Rezervasyon Fiyatı :</span></dt>
                <dd>@Model.Facility.FACILITY_PRICE TL</dd>
                <dt><span class="label" id="myLabel">Rezervasyon Tarihi :</span></dt>
                <dd>@Model.Date.ToShortDateString()</dd>
                <dt><span class="label" id="myLabel">Rezervasyon Saati :</span></dt>
                <dd>@Model.Hour</dd>
            </dl>

            @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control", placeholder = "Kişi sayısını giriniz", Value = "", @id = "txtCount" } })
            <span class="text-danger field-validation-error" id="validateCount"></span>
            @Html.HiddenFor(model => model.Date, new { @id = "hdnDate" })
            @Html.HiddenFor(model => model.Hour, new { @id = "hdnTime" })
            @Html.Hidden("hdnCapacity", Model.Facility.FACILITY_CAPACITY, new { @id = "hdnCapacity" })
            @Html.Hidden("hdnFacilityId", Model.Facility.FACILITY_ID, new { @facilityId = "hdnFacilityId" })

            <div class="col-md-offset-4">
                <button type="button" class="btn btn-success btnApprove" style="width:130px; margin-top:5px;" id="@Url.Action("Index", "Member")">
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Onayla
                </button>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/sweetalert.min.js"></script>
<link rel="stylesheet" type="text/css" href="~/css/sweetalert.css">
<script>
    $(document).ready(function () {
        $(".btnApprove").click(function () {
            var capacity = $("#hdnCapacity").val();
            var isValidate = true;
            if ($("#txtCount").val() == null || $("#txtCount").val() == "") {
                $("#validateCount").text("Lütfen kisi sayisi giriniz.")
                isValidate = false;
            }
            else if (parseInt($("#txtCount").val()) > parseInt(capacity)) {
                $("#validateCount").text("En fazla tesis kapasitesi kadar kisi sayisi girilebilir.")
                isValidate = false;
            }
            else if (parseInt($("#txtCount").val()) <= 0) {
                $("#validateCount").text("Kişi sayısı minimum 1 olabilir.")
                isValidate = false;
            }

            if (isValidate == false) {
                return false;
            }

            swal({
                title: "Emin misiniz?",
                text: "Rezervasyonu tamamlamak istediğinize emin misiniz?",
                type: "warning",
                showCancelButton: true,
                closeOnConfirm: false,
                closeOnCancel: false,
                showLoaderOnConfirm: true,
                confirmButtonText: "Evet!",
                confirmButtonColor: "#449d44",
                cancelButtonText: "Hayır"
            },
            function (isConfirm) {
                if (isConfirm == false) {
                    swal("İptal edildi", "Rezervasyondan vazgeçildi!", "error");
                }
                else {
                    var paramFacilityId = $("#hdnFacilityId").val();
                    var paramDate = $("#hdnDate").val();
                    var paramHour = $("#hdnTime").val();
                    var paramCount = $("#txtCount").val();

                    $.ajax(
                        {
                            type: "POST",
                            url: "/Reservation/Create",
                            data: { facilityId: paramFacilityId, date: paramDate, hour: paramHour, count: paramCount },
                            success: function (data) {
                                if (data) {
                                    setTimeout(function () {
                                        swal({
                                            title: "İşlem tamam!",
                                            text: "Rezervasyonun başarıyla tamamlandı!",
                                            type: "success",
                                            showCancelButton: false,
                                            closeOnConfirm: false,
                                            showLoaderOnConfirm: true,
                                            confirmButtonText: "Tamam",
                                            confirmButtonColor: "#449d44"
                                        }, function () {
                                            var url = $(".btnApprove").attr("id");
                                            window.location.href = url;
                                        });
                                    },0);
                                }
                                else {
                                    swal("Oops", "Rezervasyon tamamlanırken bir sorun oluştu!", "error");
                                }
                            }
                        })
                    .done(function (data) {
                        swal("İşlem tamam!", "Rezervasyonun başarıyla tamamlandı!", "success");
                    })
                    .error(function (data) {
                        swal("Oops", "Rezervasyon tamamlanırken bir sorun oluştu!", "error");
                    });
                }
            });
        });
    });
</script>

sahakirala/Views/Shared/_PartialSubscribe.cshtml
@model sahakirala.Models.ReservationBigModel

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color:#faebcc;">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Abonelik</h4>
            </div>
            <div class="modal-body">

                <div class="form-horizontal">
                    <div class="form-group">
                        @Html.Label("Gün ve saat seçerek tesise abone olabilirsiniz! :", htmlAttributes: new { @class = "control-label col-md-12 subscribeLabel" })
                    </div>
                    <div class="form-group">
                        @Html.Label("Gün :", htmlAttributes: new { @class = "control-label col-md-3 subscribeLabel" })
                        <div class="col-md-9" style="padding-right:30px;">
                            @Html.DropDownList("ddlDays", ViewBag.Days as SelectList, "Gün Seçiniz", new { @class = "form-control", @id = "ddlDays" })
                            <span class="text-danger field-validation-error" id="validateDay" style="padding-left:23px;"></span>
                            @*@Html.DropDownListFor(model => model.sDay, ViewBag.Days as SelectList, "Gün Seçiniz", new { @class = "form-control", @id = "ddlDays" })*@
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("Saat Aralığı :", htmlAttributes: new { @class = "control-label col-md-3 subscribeLabel" })
                        <div class="col-md-9" style="padding-right:30px;">
                            @Html.DropDownList("ddlHours", ViewBag.Hours as SelectList, "Saat Aralığı Seçiniz", new { @class = "form-control", @id = "ddlHours" })
                            <span class="text-danger field-validation-error" id="validateHour" style="padding-left:23px;"></span>
                            @*@Html.DropDownListFor(model => model.sHour, ViewBag.Hours as SelectList, "Saat Aralığı Seçiniz", new { @class = "form-control", @id = "ddlHours" })*@
                        </div>
                    </div>

                    @{ if (Model.isProblem == "Y")
                        {
                                <div class="alert alert-danger" id="dvErrors">
                                    Dikkat ! Aşağıdaki gün ve saatlerde rezervasyonlar mevcuttur. Yine de abone olmak istiyor musunuz?
                                </div>
                                <table class="table table-hover table-bordered" id="dvErrorTable">
                                    <tr>
                                        <th>
                                            Rezervasyon Tarihi
                                        </th>
                                        <th>
                                            Rezervasyon Saat Aralığı
                                        </th>
                                    </tr>
                                    @foreach (var item in Model.Reservations)
                                    {
                                        string Hour = item.DT_BEGIN.Hour.ToString();
                                        string nextHour = "";
                                        if (int.Parse(Hour) < 10)
                                        {
                                            Hour = "0" + Hour;
                                            nextHour = (int.Parse(Hour) == 9) ? "10" : "0" + (int.Parse(Hour) + 1).ToString();
                                        }
                                        else
                                        {
                                            nextHour = (int.Parse(Hour) + 1).ToString();
                                        }
                                        <tr>
                                            <td>
                                                @item.DT_BEGIN.ToShortDateString()
                                            </td>
                                            <td>
                                                @Hour:00 - @nextHour:00
                                            </td>
                                        </tr>
                                    }
                                </table>
                        }
                        else if (Model.isProblem == "N")
                        {
                            <div class="alert alert-success dvError" id="dvNoError">
                                Başarılı bir şekilde abone oldunuz.
                            </div>
                        }
                        else if (Model.isProblem == "E")
                        {
                            <div class="alert alert-danger" id="dvErrors">
                                Aynı saatte başka bir abone mevcut!
                            </div>
                        }
                    }
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">İptal</button>
                <button type="button" class="btn btn-success variableButton" id="@(Model.isProblem == "Y" ? "btnApproveSubscribe" : "btnModalSubscribe")"  >Abone Ol</button>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#btnModalSubscribe").click(function () {
            $("#validateDay").text("");
            $("#validateHour").text("");
            if ($("#ddlDays").val() == null || $("#ddlDays").val() == "") {
                $("#validateDay").text("Lütfen gün seçiniz.")
                return false;
            }
            else if ($("#ddlHours").val() == null || $("#ddlHours").val() == "") {
                $("#validateHour").text("Lütfen saat aralığı seçiniz")
                return false;
            }

            var facilityId = hdnFacility.value;
            var myDay = $("#ddlDays").val();
            var myHour = $("#ddlHours").val();
            var myHourText = $("#ddlHours option:selected").text();
            $('#myModal').modal('hide');
            $.ajax({
                url: "/Reservation/CheckSub",
                type: "GET",
                data: { id: facilityId, day: myDay, hour: myHour, hourText: myHourText }
            })
            .done(function (partialViewResult) {
                $("#partialSubscribe").html(partialViewResult);
                $('#myModal').modal('show');
                $("#ddlDays").val(myDay);
                $("#ddlHours").val(myHour);
                $("#btnModalSubscribe").attr("disabled", true);
                if ($(".dvError").attr("id") == "dvNoError") {
                    var url = '@Url.Action("Index", "Member")';
                    hrefTimeout(url);
                };
            });
        });

        $("#btnApproveSubscribe").click(function () {
            var facilityId = hdnFacility.value;
            var myDay = $("#ddlDays").val();
            var myHour = $("#ddlHours").val();
            var myHourText = $("#ddlHours option:selected").text();
            $('#myModal').modal('hide');
            $.ajax({
                url: "/Reservation/CreateSubscribe",
                type: "POST",
                crossDomain: true,
                data: { id: facilityId, day: myDay, hour: myHour, hourText: myHourText }
            })
            .done(function (data) {
                $("#ddlDays").val(myDay);
                $("#ddlHours").val(myHour);
                swal("Abonelik!", "Aboneliğiniz iletilmiştir!", "success")
                var url = '@Url.Action("Index", "Member")';
                hrefTimeout(url);
            });
        });
    });

    function hrefTimeout(url) {
        setTimeout(function () { window.location.href = url }, 2000);
    }
</script>